### ISSUE TITLE
Paintball - Desert Warfare: blocks are all still broken from 1.13 conversion

### ISSUE THREAD

**Issue by WakkaFlocka239** [Pugabyte/BearNation#498]
all fences and stairs need a once over
<img src=https://i.imgur.com/sFXsjwA.jpeg>

**Comment by WakkaFlocka239** [comment]
Arctic Combat has similar problems

**Comment by WakkaFlocka239** [comment]
Also, when your snowball hits a dead bush in Desert Warfare, it breaks it

**Comment by JustSteveThings** [comment]
Fixed

**Comment by WakkaFlocka239** [comment]
Still broken, all maps still have broken fences and stairs
ArcticCombat
<img src=https://i.imgur.com/WM3WZmx.jpg>

DesertWarfare
<img src=https://i.imgur.com/surIo54.jpeg>
<img src=https://i.imgur.com/Hl2Z86Q.jpg>

Colormatic
<img src=https://i.imgur.com/nKoIdxQ.jpg>

CocytusPain
<img src=https://i.imgur.com/2B94aad.jpg>

**Comment by lexikiq** [comment]
fixed all i could find (except ones i thought looked good)
